[package]
name = "quote_verifier"
type = "contract"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-nr", tag = "v4.3.0", directory = "aztec" }
attestation_verifier = { path = "../../attestation_verifier" }
