[package]
name = "option_escrow"
type = "contract"
compiler_version = ">=1.0.0"
authors = [""]

[dependencies]
aztec = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.3.0", directory = "noir-projects/aztec-nr/aztec" }
public_checks_contract = { git = "https://github.com/AztecProtocol/aztec-packages/", tag = "v4.3.0", directory = "noir-projects/noir-contracts/contracts/protocol/public_checks_contract" }
escrow_standard = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "prerelease-eca9816", directory = "src/escrow_contract" }
token = { git = "https://github.com/defi-wonderland/aztec-standards/", tag = "prerelease-eca9816", directory = "src/token_contract" }
klines_oracle = { path = "../klines_oracle" }
